// ini cara nge hit endpoint post
// content-type ini buat ngasih tau server, request datanya tuh JSON
POST http://localhost:8080/event
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyOTE1NTQwLCJ1c2VySWQiOjN9.YvBzkvjhyb8SQRSjf18OMdkxOpxesTKXBQuboMMi3_4

{
    "Name": "tes",
    "Description": "tes event new!",
    "Location": "bogor",
    "DateTime": "2026-04-25T12:00:00.000Z"
}